---
abstract: 'OpenID Connect Library'
author:
  - 'Ryo Ito <ritou.06@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OIDC-Lite
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0.34
  Data::Dump: 1.17
  JSON::WebToken: 0.05
  OAuth::Lite2: 0.03
  Params::Validate: 0.95
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
